name: Ticket Monitor

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Actualizado a v4

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Actualizado a v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run monitor
        run: node monitor.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Upload debug files
        if: failure()
        uses: actions/upload-artifact@v4  # Actualizado a v4
        with:
          name: debug-files
          path: |
            debug.png
            debug.html