name: Ticket Monitor

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Setup Playwright and browsers
        uses: microsoft/playwright-github-action@v1
        with:
          install-deps: true   # Instala dependencias del sistema necesarias
          browsers: chromium    # Solo Chromium, suficiente para tu monitor

      - name: Install project dependencies
        run: npm install

      - name: Run monitor
        run: npm start
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

