name: Ticket Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # ⏰ Cada 5 minutos
  workflow_dispatch:       # Permite lanzarlo manualmente también

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run monitor
        run: npm start
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
